{% set name = "ellc" %}
{% set version = "1.8.8" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ellc-{{ version }}.tar.gz
  sha256: a0b7aaf9861b53ab5bf5ef73644549a8f4a36eed0d05356f045e957956ada5af

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('fortran') }}
  host:
    - numpy
    - pip
    - python
  run:
    - astropy >=1.1.1
    - numpy >=1.10.0
    - python
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - ellc
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pmaxted/ellc
  summary: Light curve model for eclipsing binary stars and transiting exoplanets
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - mwcraig
